#include <iostream>
using namespace std;
main() {
int numb1;
int numb2;
int numb3;
int numb4;
int numb5;
int numb6;
int numb7;
int numb8;
int numb9;
int numb10;
int numb11;
int numb12;
int numb13;
int numb14;
int numb15;
int total_1;
int total_2;
int total_3;
int total;
cout<<"Enter integer 1";
cin>>numb1;
cout<<"Enter integer2";
cin>>numb2;
cout<<"Enter integer3";
cin>>numb3;
cout<<"Enter integer4";
cin>>numb4;
cout<<"Enter integer5";
cin>>numb5;
cout<<"Enter integer6";
cin>>numb6;
cout<<"Enter integer7";
cin>>numb7;
cout<<"Enter integer8";
cin>>numb8;
cout<<"Enter integer9";
cin>>numb9;
cout<<"Enter integer10";
cin>>numb10;
cout<<"Enter integer11";
cin>>numb11;
cout<<"Enter integer12";
cin>>numb12;
cout<<"Enter integer13";
cin>>numb13;
cout<<"Enter integer14";
cin>>numb14;
cout<<"Enter integer15";
cin>>numb15;
total_1= numb1+numb2+numb3+numb4+numb5;
total_2= numb6*numb7*numb8*numb9*numb10;
total_3= numb11-numb12-numb13-numb14-numb15;
total =(total_1+total_2) -total_3;
cout<<"total="<<total;
}
